from src.interface.components.ModelInfoWidget import ModelInfoWidget
from src.interface.components.ModelListWidget import ModelListWidget
from src.interface.components.SplashScreen import SplashScreen
from src.interface.components.ClassificationLabelButtonsWidget import ClassificationLabelButtonsWidget
from src.interface.components.AudioPlayerWidget import AudioPlayerWidget
